[package]
name = "axel"
version = "0.1.0"
edition = "2021"
description = "The Laravel of rust web frameworks & tooling"
authors=["Jacobtread"]
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
